language: objective-c

osx_image: xcode8.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilCrypto.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilCrypto iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilCrypto macOS"
    - IOS_SDK=iphonesimulator10.3
    - MACOS_SDK=macosx10.12
    - FRAMEWORK_NAME=VirgilCrypto
  matrix:
    - DESTINATION="OS=10.3,name=iPhone SE"     SCHEME="$IOS_FRAMEWORK_SCHEME"    SDK="$IOS_SDK"    CARTHAGE_PLATFORM_NAME="iOS"  RUN_TESTS="YES"
    - DESTINATION="arch=x86_64"                SCHEME="$MACOS_FRAMEWORK_SCHEME"  SDK="$MACOS_SDK"  CARTHAGE_PLATFORM_NAME="Mac"  RUN_TESTS="YES"

before_install:
  - set -o pipefail
  - brew update 
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

language: objective-c

script:
  # Build Framework
  - xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean build-for-testing | xcpretty;
  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release GCC_GENERATE_TEST_COVERAGE_FILES=YES test-without-building | xcpretty;
    fi

# deploy:
#   - provider: releases
#     api_key:
#       secure: KoovDyi1gvzeDdGWKUPq2IEkpiC/6PadkIVEEkh+lyqBpWliC3KOu3cD/RXBAJw84g+YNUFr80776Xv/QPdj1LzTaN0Ri2HpfdyEPFOHvhQKzxJG/jm4BZBV+CNJfLJZndvrF/ImeZgkRTk/MR83urBJfl4/UnPj77CZg+lpG88HtV3oN8OqxBPEy34D4MTsg3twL/Z/XYlYl3BMzVzJzY9teHxwwcEgYwsk8i0GUggTRO/cyTDqg9X/g1rqEPWzlX4S/hGVBCB6qrRrXXK96DYUic39LdNbt+so+8hJHO0ETxTtt7v1B59qZ0OUlQfSBeUqBIrJCFm3U7hR4UJqHbsUl3dyQ/WrZv28/AaAFYCRDTqZSE7oTXR9IhY+jlhLrU3n7ukYoG1Yhr11MQN1z8DgzIhdyWWX2DK16kgsIFC99AxkRQzmJdQqXMmtrR79UN0/8eKE4WAm8Ihji6fTTCm4zx3sfi1bTJ8bdzbFhgpqqUpAuKc7yGbOhRsnYsL+TTpQiVCGju/nUNEHmwUy+MmYkHlR8l1OHz0mGbZQMecUXZ8h4Be7RONIOaDB05Gi4wkcaywDkoUdEb9LuFIme+Ws+PbNEKwkcPIiv9tGzh/ROk9t7qWj3FU3R1oLQImpwBbIlywyelWrNfWE5QG928UmYNyK1RrpRBL8ekqqXlw=
#     file: $FRAMEWORK_NAME.framework.zip
#     skip_cleanup: true
#     on:
#       repo: VirgilSecurity/virgil-foundation-x
#       tags: true
